version: '2'

services:
  python-flask-sgx:
    image: ritesh-enclaive/python-flask-sgx
    container_name: "python-flask-sgx"
    build:
      context: .
    ports:
      - "5000:5000"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"

  python-flask-nosgx:
    image: ritesh-enclaive/python-flask-sgx
    container_name: "python-flask-nosgx"
    build:
      context: .
    ports:
      - "5000:5000"
    entrypoint: ""
    command: "python3 /app/main.py"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
