apiVersion: v1
kind: Service
metadata:
  name: payr-payment-service-normal
spec:
  selector:
    app: flask-service-normal-pod
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    nodePort: 30385
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-normal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-service-normal-pod
  template:
    metadata:
      labels:
        app: flask-service-normal-pod
    spec:
      containers:
      - name: flask-normal-pod
        image: ritesh-enclaive/python-flask-sgx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /dev/nosgx_enclave
          name: nosgx-enclaive
        securityContext:
          privileged: true
        command: ["/usr/bin/python3", "/app/main.py"]
      nodeName: node7
      volumes:
      - name: nosgx-enclaive
        hostPath:
          path: /dev/nosgx_enclave

