apiVersion: v1
kind: Service
metadata:
  name: payr-payment-service-confidential
spec:
  selector:
    app: flask-service-sgx-pod
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    nodePort: 30384
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sgx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-service-sgx-pod
  template:
    metadata:
      labels:
        app: flask-service-sgx-pod
    spec:
      containers:
      - name: flask-sgx-pod
        image: ritesh-enclaive/python-flask-sgx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /dev/sgx_enclave
          name: sgx-enclaive
        securityContext:
          privileged: true
      nodeName: node7
      volumes:
      - name: sgx-enclaive
        hostPath:
          path: /dev/sgx_enclave

